name: Build Packagist Repository

on: 
  push:
    branches: 
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [regenerate, update]
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest
        extensions: mbstring
        tools: composer
      env:
        fail-fast: true
    - name: Checkout Pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: pages 
    - name: Checkout configurations
      uses: actions/checkout@v2
      with: 
        ref: master 
        path: conf 
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: '~/.cache/composer/files'
        key: composer-cache
    - name: Install Satis
      run: composer create-project --remove-vcs composer/satis:dev-master ./satis
    - name: Run Satis (Full Build)
      if: |
        github.event_name == 'workflow_dispatch' || 
        github.event_name == 'push' || 
        (github.event_name == 'repository_dispatch' && github.event.action == 'regenerate')
      run: php satis/bin/satis build conf/satis.json pages
    - name: Run Satis (Partial Build)
      if: |
        github.event_name == 'repository_dispatch' && github.event.action == 'update'
      run: php satis/bin/satis build --repository-url ${{github.event.client-payload.repo}} conf/satis.json pages
    - name: Upload changes to Pages
      continue-on-error: true
      run: |
        cd pages
        git config --local user.name 'github-actions'
        git config --local user.email 'github-actions@users.noreply.github.com'
        git add --all
        git commit -m "ci(update): Update satis repository"
        git push
